// export const useractions = {
    

//     LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
//     LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
//     LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
//     LOGIN_ERROR: 'USERS_LOGIN_ERROR',
//     LOGIN_CANCELLED:'USERS_LOGIN_CANCELLED',
//     SAVE_TOKEN: 'USERS_SAVE_TOKEN',
//     DELETE_TOKEN: 'USERS_DELETE_TOKEN',
//     LOGOUT: 'USERS_LOGOUT',

// };
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export default {
  LOGIN_REQUEST,
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  LOGIN_CANCELLED,
  SAVE_TOKEN,
  DELETE_TOKEN,
};